### ISSUE TITLE
Info request to help fill in missing flight points

### ISSUE THREAD

**Issue by mwpatrick** [datagutten/FlightMastersClassic#1]
Hi there. I'm wondering how you determine the NPC and map numbers in the flight_masters_* structures? 

ex: { npc = 2859, name = "Gyll", coords = { 27.4, 77.6 }, map = 1434 }

I'm asking because I notice Alliance is missing the flight master for Ashenvale. If I know how NPC and map are determined I can file a PR to add the flight point.

An additional thought - would it be permissible to add "Flight:" to their name so it is obvious on the map WHY they are a preset in TomTom?

**Comment by datagutten** [comment]
The current list is based on wowhead data, but I am planning to use the API instead. I currently have some problems with the API returning points which is not flight masters, so I need to add some filtering.
The API call I am using is C_TaxiMap.GetTaxiNodesForMap

**Comment by datagutten** [comment]
"Flight:" before the name will be added.

**Comment by mwpatrick** [comment]
Updated my existing open pull request with another flight point I found.

**Comment by mwpatrick** [comment]
Hmm - I see your API branch. Trying it out, I see what you mean about some kind of filtering - for example Naxxramas? Also as Alliance I probably don't much care about Horde flight points and vice-versa. Although that might be an interesting toggle option, maybe with a different map color pin.

If https://wow.gamepedia.com/API_C_TaxiMap.GetTaxiNodesForMap is right, there is a faction property on the returned taxi object. There is probably a way to get the faction of the player but I'm too tired at the moment to find it. That would take care of the other faction flight points.

Seems like someone else is running into the same trouble you are (or maybe this is you): https://us.forums.blizzard.com/en/wow/t/api-issues-with-classic/305115
